image: gitpod/workspace-base

tasks:
  - name: Start with dependencies
    init: >
     sudo apt-get update && sudo apt install mosquitto-clients python3-pip nodejs npm -y &&
      sudo apt install openjdk-17-jre -y  && pip install python-dotenv invoke &&
       invoke -c services build -p && sudo npm install -g newman newman-reporter-json-summary


ports:
  - name: Orion
    description: Context Broker
    port: 1026
    onOpen: notify
  - name: Keyrock
    description: Identity Manager
    port: 3005
    onOpen: open-preview
  - name: IoT Agent (North Port)
    description: NGSI data and device provisioning
    port: 4041
    onOpen: ignore
  - name: IoT Agent (South Port)
    description: Ultralight HTTP measures
    port: 7896
    onOpen: ignore
  - name: Pep proxy
    description: Ultralight HTTP measures
    port: 7897
    onOpen: ignore
